HAYVAN_BILGILERI = {
    "aslan": {
        "siniflandirma": "Memeli, Etçil (Carnivore)",
        "beslenme": "Büyük otçulları (zebra, geyik) avlar ve etle beslenir.",
        "yasama_alani": "Afrika'daki savanlar ve açık otlaklar.",
        "omur": "Vahşi doğada ortalama 10-14 yıl.",
        "hiz": 80, 
        "ağırlık_kg": 190, 
        "boyut_m": 1.2,
        "koruma_durumu": "Hassas (Vulnerable)",
        "yetenekler": "Geceleri avlanır, kısa mesafede hızlı koşar, güçlü pençeleri vardır."
    },
    "kaplan": {
        "siniflandirma": "Memeli, Etçil (Carnivore)",
        "beslenme": "Geyik, yaban domuzu ve sığır gibi büyük avları yer.",
        "yasama_alani": "Asya'nın ormanlık ve çimenlik bölgeleri.",
        "omur": "Vahşi doğada ortalama 10-15 yıl.",
        "hiz": 65, 
        "ağırlık_kg": 220, 
        "boyut_m": 1.0,
        "koruma_durumu": "Tehlikede (Endangered)",
        "yetenekler": "Mükemmel yüzücüdür, ağaçlara tırmanabilir, pusu avcısıdır."
    },
    "panda": {
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Neredeyse tamamen bambu ile beslenir, nadiren küçük kemirgenler.",
        "yasama_alani": "Çin'in dağlık ormanlık bölgeleri.",
        "omur": "Vahşi doğada ortalama 15-20 yıl.",
        "hiz": 30, 
        "ağırlık_kg": 110, 
        "boyut_m": 1.5,
        "koruma_durumu": "Hassas (Vulnerable)",
        "yetenekler": "Mükemmel tırmanıcıdır, bambu liflerini sindirebilen özel bir sindirim sistemine sahiptir."
    },
    "fil": {
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Ot, yaprak ve meyve gibi günde yüzlerce kilogram bitkisel madde yer.",
        "yasama_alani": "Afrika ve Asya'nın savan, ormanlık ve çöl bölgeleri.",
        "omur": "Ortalama 60-70 yıl.",
        "hiz": 40, 
        "ağırlık_kg": 6000, 
        "boyut_m": 3.3,
        "koruma_durumu": "Tehlikede (Endangered)",
        "yetenekler": "Mükemmel hafızaya ve yüzme yeteneğine sahiptir."
    },
    "zürafa": {
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Akasya ağacının yaprakları ve filizleriyle beslenir.",
        "yasama_alani": "Afrika'daki savanlar ve açık ormanlık alanlar.",
        "omur": "Ortalama 25 yıl.",
        "hiz": 55, 
        "ağırlık_kg": 1190, 
        "boyut_m": 5.5,
        "koruma_durumu": "Hassas (Vulnerable)",
        "yetenekler": "Çok hızlı koşabilir ve uzun boyu sayesinde en yüksek dallara ulaşabilir."
    },
    "penguen": {
        "siniflandirma": "Kuş (Avian), Etçil (Carnivore)",
        "beslenme": "Balık, kalamar ve kril (küçük kabuklular) ile beslenir.",
        "yasama_alani": "Güney Kutbu (Antarktika) ve Güney Yarımküre'nin soğuk kıyıları.",
        "omur": "Türüne göre 15-20 yıl.",
        "hiz": 10, 
        "ağırlık_kg": 40, 
        "boyut_m": 1.1,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Uçamaz ancak mükemmel bir yüzücü ve dalgıçtır."
    },
    "köpekbalığı": {
        "siniflandirma": "Kıkırdaklı Balık, Etçil (Carnivore)",
        "beslenme": "Balık, fok, deniz aslanı ve bazen diğer köpekbalıkları.",
        "yasama_alani": "Dünyadaki tüm okyanus ve denizler.",
        "omur": "Büyük beyaz köpekbalığı 70 yıla kadar yaşayabilir.",
        "hiz": 56, 
        "ağırlık_kg": 1100, 
        "boyut_m": 6.0,
        "koruma_durumu": "Hassas (Vulnerable)",
        "yetenekler": "Elektriksel alanları algılayabilir, sürekli hareket etmelidir."
    },
    "timsah": {
        "siniflandirma": "Sürüngen (Reptile), Etçil (Carnivore)",
        "beslenme": "Balık, memeliler, kuşlar ve diğer sürüngenler.",
        "yasama_alani": "Afrika, Asya, Amerika ve Avustralya'nın tatlı su nehirleri ve bataklıkları.",
        "omur": "Ortalama 50-60 yıl.",
        "hiz": 29, 
        "ağırlık_kg": 500, 
        "boyut_m": 4.5,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Sudaki hızı çok yüksektir, karada kısa mesafelerde hızlanabilir, çok güçlü çenesi vardır."
    },
    "kartal": {
        "siniflandirma": "Kuş (Avian), Etçil (Carnivore)",
        "beslenme": "Küçük memeliler, kuşlar, balıklar ve leşler.",
        "yasama_alani": "Dağlık bölgeler, ormanlar ve kıyı şeritleri.",
        "omur": "Vahşi doğada 20-30 yıl.",
        "hiz": 160, 
        "ağırlık_kg": 5, 
        "boyut_m": 0.8,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Mükemmel görüşe ve avlanma için yüksek hıza sahiptir (dalışta)."
    },
    "kedi": {
        "siniflandirma": "Memeli, Etçil (Carnivore)",
        "beslenme": "Protein ağırlıklı beslenir; fare, kuş ve balık yer.",
        "yasama_alani": "Evcilleşmiş (tüm dünya) ve vahşi.",
        "omur": "Ortalama 12-18 yıl.",
        "hiz": 48, 
        "ağırlık_kg": 4, 
        "boyut_m": 0.5,
        "koruma_durumu": "Evcil Hayvan",
        "yetenekler": "Esnek vücuda sahiptir, yüksekten düşüşleri tolere edebilir, çok iyi tırmanıcıdır."
    },
    "kaplumbağa": {
        "siniflandirma": "Sürüngen (Reptile), Otçul/Etçil (Türe göre değişir)",
        "beslenme": "Çoğunlukla ot, yaprak ve meyveler. Deniz kaplumbağaları denizanası yer.",
        "yasama_alani": "Dünyanın tropikal ve ılıman bölgeleri (kara ve deniz).",
        "omur": "Büyük kara kaplumbağaları 100 yıldan fazla yaşayabilir.",
        "hiz": 0.3, 
        "ağırlık_kg": 150, 
        "boyut_m": 1.0,
        "koruma_durumu": "Çeşitli (Çoğu Hassas)",
        "yetenekler": "Kabuğunun içine çekilebilir, bazı türleri inanılmaz uzun ömürlüdür."
    },
    "su aygırı": { 
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Temel olarak su bitkileri ve otlarla beslenir.",
        "yasama_alani": "Afrika'nın nehirleri ve gölleri.",
        "omur": "Ortalama 40-50 yıl.",
        "hiz": 30, 
        "ağırlık_kg": 1500, 
        "boyut_m": 1.5,
        "koruma_durumu": "Hassas (Vulnerable)",
        "yetenekler": "Su altında çok iyi manevra yapar, karada şaşırtıcı derecede hızlı koşabilir."
    },
    "ornitorenk": { 
        "siniflandirma": "Memeli (Tek delikliler-Monotreme), Etçil",
        "beslenme": "Nehir yataklarından böcek, solucan ve küçük kabukluları avlar.",
        "yasama_alani": "Doğu Avustralya ve Tazmanya'daki tatlı su nehirleri.",
        "omur": "Ortalama 17 yıl.",
        "hiz": 10, 
        "ağırlık_kg": 2, 
        "boyut_m": 0.5,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Memeliler arasında yumurtlayan nadir türdür, erkeklerde zehirli mahmuz bulunur."
    },
    "komodo ejderi": { 
        "siniflandirma": "Sürüngen (Reptile), Etçil (Carnivore)",
        "beslenme": "Büyük memeliler (su bufalosu, geyik) ve leş yer.",
        "yasama_alani": "Endonezya'daki Komodo, Rinca, Flores ve Gili Motang adaları.",
        "omur": "Ortalama 30 yıl.",
        "hiz": 20, 
        "ağırlık_kg": 90, 
        "boyut_m": 3.0,
        "koruma_durumu": "Hassas (Vulnerable)",
        "yetenekler": "Zehirli ısırığı vardır, güçlü pençeleri ve keskin dişleri bulunur."
    },
    "mavi balina": { 
        "siniflandirma": "Memeli, Etçil (Krillivore)",
        "beslenme": "Krill (küçük karides benzeri kabuklular) ile beslenir, günde 4 tona kadar krill yiyebilir.",
        "yasama_alani": "Dünyadaki tüm okyanuslar.",
        "omur": "Ortalama 80-90 yıl.",
        "hiz": 48, 
        "ağırlık_kg": 140000, 
        "boyut_m": 25.0,
        "koruma_durumu": "Tehlikede (Endangered)",
        "yetenekler": "Dünyanın en büyük hayvanıdır, uzun süre su altında kalabilir."
    },
    "imparator pengueni": { 
        "siniflandirma": "Kuş (Avian), Etçil (Carnivore)",
        "beslenme": "Balık, kalamar ve kril.",
        "yasama_alani": "Antarktika'nın buzulları.",
        "omur": "Ortalama 20 yıl.",
        "hiz": 6, 
        "ağırlık_kg": 30, 
        "boyut_m": 1.2,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Tüm penguenler arasında en uzun süre dalış yapabilen ve en soğuk koşullara dayanabilen türdür."
    },
    "alabalık": {
        "siniflandirma": "Işınsal Yüzgeçli Balık, Etçil (Carnivore)",
        "beslenme": "Böcekler, küçük balıklar ve omurgasızlar.",
        "yasama_alani": "Soğuk, temiz tatlı su nehirleri ve gölleri.",
        "omur": "Türüne göre 5-10 yıl.",
        "hiz": 30, 
        "ağırlık_kg": 1, 
        "boyut_m": 0.5,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Yüksek hızda kısa mesafelerde yüzebilir, akıntıya karşı zıplayabilir."
    },
    "sazan": {
        "siniflandirma": "Işınsal Yüzgeçli Balık, Otçul/Hepçil (Omnivore)",
        "beslenme": "Su bitkileri, yosunlar ve küçük omurgasızlar.",
        "yasama_alani": "Ilık, durgun veya yavaş akan tatlı sular (göletler ve nehirler).",
        "omur": "Ortalama 20 yıl, bazıları 40 yıla kadar.",
        "hiz": 15, 
        "ağırlık_kg": 20, 
        "boyut_m": 0.7,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Dibe yakın yiyecek arar, çok dayanıklı ve uzun ömürlü bir balık türüdür."
    },
    "şahin": {
        "siniflandirma": "Kuş (Avian), Etçil (Carnivore)",
        "beslenme": "Küçük memeliler, sürüngenler ve kuşlar.",
        "yasama_alani": "Açık ormanlık alanlar, tarlalar ve dağlık bölgeler.",
        "omur": "Vahşi doğada 10-15 yıl.",
        "hiz": 150, 
        "ağırlık_kg": 1.5, 
        "boyut_m": 0.6,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Çok yüksekten süzülebilir, keskin görüşe ve etkileyici dalış hızına sahiptir."
    },
    "kanarya": {
        "siniflandirma": "Kuş (Avian), Otçul (Herbivore)",
        "beslenme": "Tohumlar, otlar ve meyveler.",
        "yasama_alani": "Kanarya Adaları, Azorlar ve Madeira (Evcilleşmiş tüm dünya).",
        "omur": "Ortalama 10 yıl.",
        "hiz": 50, 
        "ağırlık_kg": 0.02, 
        "boyut_m": 0.15,
        "koruma_durumu": "Evcil Hayvan",
        "yetenekler": "Güzel ve çeşitli şarkılarıyla ünlüdür."
    },
    "flamingo": {
        "siniflandirma": "Kuş (Avian), Etçil (Carnivore)",
        "beslenme": "Mavi-yeşil algler, küçük böcekler ve larvalar (Renklerini krill'den alırlar).",
        "yasama_alani": "Büyük sığ göller ve lagünler.",
        "omur": "Vahşi doğada 30 yıla kadar.",
        "hiz": 56, 
        "ağırlık_kg": 3, 
        "boyut_m": 1.5,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Tek ayak üzerinde durabilir, uzun mesafeler göç edebilir."
    },
    "devekuşu": {
        "siniflandirma": "Kuş (Avian), Otçul/Hepçil (Omnivore)",
        "beslenme": "Tohumlar, otlar, meyveler ve böcekler.",
        "yasama_alani": "Afrika'nın savanları ve yarı kurak bölgeleri.",
        "omur": "Ortalama 50 yıl.",
        "hiz": 70, 
        "ağırlık_kg": 150, 
        "boyut_m": 2.5,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Uçamaz ancak iki parmaklı güçlü ayakları sayesinde saatte 70 km hıza ulaşabilen en hızlı koşucu kuştur."
    },
    "gergedan": {
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Otlar, yapraklar, çalılar ve meyveler.",
        "yasama_alani": "Afrika ve Asya'nın tropikal ormanları ve savanları.",
        "omur": "Ortalama 40-50 yıl.",
        "hiz": 55, 
        "ağırlık_kg": 2000, 
        "boyut_m": 1.8,
        "koruma_durumu": "Kritik Tehlikede",
        "yetenekler": "Kalın zırh benzeri derisi ve güçlü boynuzu vardır."
    },
    "boa": {
        "siniflandirma": "Sürüngen (Reptile), Etçil (Carnivore)",
        "beslenme": "Kuşlar, kemirgenler ve küçük memeliler.",
        "yasama_alani": "Orta ve Güney Amerika'nın yağmur ormanları.",
        "omur": "Ortalama 20-30 yıl.",
        "hiz": 1, 
        "ağırlık_kg": 30, 
        "boyut_m": 3.0,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Zehirsizdir, avını boğarak öldürür ve ağaçlara tırmanabilir."
    },
    "rakun": {
        "siniflandirma": "Memeli, Hepçil (Omnivore)",
        "beslenme": "Yemişler, böcekler, kemirgenler, yumurtalar ve çöp.",
        "yasama_alani": "Kuzey Amerika'nın ormanları ve şehirleri.",
        "omur": "Ortalama 2-3 yıl (vahşi doğada).",
        "hiz": 24, 
        "ağırlık_kg": 8, 
        "boyut_m": 0.6,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Mükemmel el becerilerine sahiptir, yiyeceklerini yıkamasıyla bilinir."
    },
    "çita": {
        "siniflandirma": "Memeli, Etçil (Carnivore)",
        "beslenme": "Küçük ve orta boy antiloplar, ceylanlar.",
        "yasama_alani": "Afrika'nın savanları ve otlakları.",
        "omur": "Ortalama 10-12 yıl.",
        "hiz": 120, 
        "ağırlık_kg": 60, 
        "boyut_m": 0.8,
        "koruma_durumu": "Hassas (Vulnerable)",
        "yetenekler": "Karadaki en hızlı hayvandır, hızını kısa sürede sıfırdan 100 km/s'ye çıkarabilir."
    },
    "kızıl geyik": {
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Otlar, çalılar, yapraklar ve ağaç kabukları.",
        "yasama_alani": "Türkiye'nin ormanlık ve çalılık alanları (Anadolu, Trakya).",
        "omur": "Ortalama 10-20 yıl.",
        "hiz": 70, 
        "ağırlık_kg": 250, 
        "boyut_m": 1.4,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Mükemmel işitme ve koku alma duyusuna sahiptir, güçlü boynuzları vardır."
    },
    "ankara kedisi": {
        "siniflandirma": "Memeli, Etçil (Carnivore)",
        "beslenme": "Protein ağırlıklı beslenir.",
        "yasama_alani": "Türkiye kökenli evcil kediler.",
        "omur": "Ortalama 12-18 yıl.",
        "hiz": 40, 
        "ağırlık_kg": 5, 
        "boyut_m": 0.3,
        "koruma_durumu": "Evcil Hayvan",
        "yetenekler": "Uzun, ipeksi beyaz tüyleri ve genellikle farklı renklerde gözleri vardır."
    },
    "caretta": {
        "siniflandirma": "Sürüngen (Reptile), Etçil",
        "beslenme": "Denizanası, deniz salyangozları ve kabuklu deniz canlıları.",
        "yasama_alani": "Akdeniz'in kıyıları (Türkiye'de yuvalama alanları Fethiye, Kaş, Dalyan).",
        "omur": "Ortalama 70-90 yıl.",
        "hiz": 24, 
        "ağırlık_kg": 150, 
        "boyut_m": 1.0,
        "koruma_durumu": "Tehlikede (Endangered)",
        "yetenekler": "Okyanuslarda uzun mesafeler göç eder ve yön bulma yeteneği gelişmiştir."
    },
    "kızıl akbaba": {
        "siniflandirma": "Kuş (Avian), Leşçil (Scavenger)",
        "beslenme": "Temel olarak ölü hayvan leşleri (doğanın temizleyicisi).",
        "yasama_alani": "Yüksek dağlık bölgeler, kayalık yamaçlar (Türkiye'de Doğu ve İç Anadolu).",
        "omur": "Ortalama 30-40 yıl.",
        "hiz": 60, 
        "ağırlık_kg": 8, 
        "boyut_m": 1.2,
        "koruma_durumu": "Yakın Tehdit",
        "yetenekler": "Geniş kanat açıklığı ile çok yükseklikte uzun süre süzülebilir."
    },
    "semender": {
        "siniflandirma": "Amfibi (Amphibian), Etçil (Carnivore)",
        "beslenme": "Böcekler, solucanlar ve sümüklü böcekler.",
        "yasama_alani": "Nemli ormanlık alanlar ve su kenarları (Türkiye'nin Karadeniz ve Akdeniz bölgeleri).",
        "omur": "Ortalama 6-15 yıl.",
        "hiz": 0.5, 
        "ağırlık_kg": 0.1, 
        "boyut_m": 0.2,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Zarar gören uzuvlarını yenileyebilir ve derisi zehirli salgılar üretebilir."
    },
    "zebra": {
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Otlar, çimenler ve yapraklar.",
        "yasama_alani": "Afrika'nın savanları ve otlakları.",
        "omur": "Ortalama 20-30 yıl.",
        "hiz": 65, 
        "ağırlık_kg": 350, 
        "boyut_m": 1.4,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Hızlı koşucudur, yırtıcıları şaşırtmak için çizgili kamuflaj kullanır."
    },
    "ayı": {
        "siniflandirma": "Memeli, Hepçil (Omnivore)",
        "beslenme": "Balık, böğürtlen, kökler, bal ve küçük memeliler.",
        "yasama_alani": "Ormanlık ve dağlık bölgeler (türüne göre değişir).",
        "omur": "Ortalama 20-25 yıl.",
        "hiz": 56, 
        "ağırlık_kg": 300, 
        "boyut_m": 1.8,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Ağaçlara tırmanabilir, kış uykusuna yatar, çok güçlüdür."
    },
    "kurbağa": {
        "siniflandirma": "Amfibi (Amphibian), Etçil (Carnivore)",
        "beslenme": "Böcekler, solucanlar ve küçük omurgasızlar (dillerini fırlatırlar).",
        "yasama_alani": "Tatlı su ve nemli karasal alanlar.",
        "omur": "Ortalama 5-15 yıl.",
        "hiz": 8, 
        "ağırlık_kg": 0.1, 
        "boyut_m": 0.1,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Derileri aracılığıyla solunum yapabilirler, sudan karaya geçiş yapabilirler."
    },
    "yılan": {
        "siniflandirma": "Sürüngen (Reptile), Etçil (Carnivore)",
        "beslenme": "Kemirgenler, kuşlar, yumurtalar ve diğer küçük hayvanlar.",
        "yasama_alani": "Tüm kıtalar (Antarktika hariç), çöllerden ormanlara.",
        "omur": "Türüne göre 10-30 yıl.",
        "hiz": 1, 
        "ağırlık_kg": 15, 
        "boyut_m": 2.5,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Koku ve ısı sensörleri ile avlanır, bazıları zehirlidir, avını sararak öldürür."
    },
    "ahtapot": {
        "siniflandirma": "Yumuşakçalar (Cephalopod), Etçil (Carnivore)",
        "beslenme": "Yengeçler, ıstakozlar ve diğer kabuklular.",
        "yasama_alani": "Dünyanın her yerindeki okyanuslar.",
        "omur": "Türüne göre 1-5 yıl.",
        "hiz": 40, 
        "ağırlık_kg": 50, 
        "boyut_m": 1.0,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Mükemmel kamuflaj yeteneği vardır, mürekkep püskürtebilir, zekidir."
    },
    "yunus": {
        "siniflandirma": "Memeli (Marine), Etçil (Carnivore)",
        "beslenme": "Balık ve kalamar.",
        "yasama_alani": "Okyanuslar ve bazı nehirler.",
        "omur": "Ortalama 30-50 yıl.",
        "hiz": 60, 
        "ağırlık_kg": 300, 
        "boyut_m": 3.0,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Yüksek zekaya, karmaşık sosyal yapılara ve sonar (ekolokasyon) yeteneğine sahiptir."
    },
    "şempanze": {
        "siniflandirma": "Memeli (Primat), Hepçil (Omnivore)",
        "beslenme": "Meyve, yaprak, tohum, böcek ve küçük memeliler.",
        "yasama_alani": "Batı ve Orta Afrika'nın tropik ormanları.",
        "omur": "Ortalama 40-60 yıl.",
        "hiz": 40, 
        "ağırlık_kg": 55, 
        "boyut_m": 1.2,
        "koruma_durumu": "Tehlikede (Endangered)",
        "yetenekler": "Araç gereç kullanabilir, sosyal öğrenme ve problem çözme yeteneği çok gelişmiştir."
    },
    "baykuş": {
        "siniflandirma": "Kuş (Avian), Etçil (Carnivore)",
        "beslenme": "Kemirgenler, böcekler ve küçük kuşlar.",
        "yasama_alani": "Tüm dünyadaki ormanlık ve ağaçlık alanlar.",
        "omur": "Ortalama 10-20 yıl.",
        "hiz": 65, 
        "ağırlık_kg": 0.5, 
        "boyut_m": 0.4,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Sessiz uçuş yeteneği ve mükemmel gece görüşüne sahiptir."
    },
    "kertenkele": {
        "siniflandirma": "Sürüngen (Reptile), Etçil/Otçul (Türe göre değişir)",
        "beslenme": "Böcekler, bitkiler ve diğer küçük sürüngenler.",
        "yasama_alani": "Çöller, ormanlar ve şehirler dahil olmak üzere tüm dünyada.",
        "omur": "Ortalama 5-20 yıl.",
        "hiz": 20, 
        "ağırlık_kg": 0.1, 
        "boyut_m": 0.3,
        "koruma_durumu": "En Az Endişe Veren",
        "yetenekler": "Hızlı hareket edebilir ve bazı türler kuyruklarını bırakarak yırtıcılardan kaçabilir."
    },
    "bizon": {
        "siniflandirma": "Memeli, Otçul (Herbivore)",
        "beslenme": "Ot ve çimen.",
        "yasama_alani": "Kuzey Amerika'nın otlakları ve ovaları.",
        "omur": "Ortalama 15-20 yıl.",
        "hiz": 60, 
        "ağırlık_kg": 900, 
        "boyut_m": 1.8,
        "koruma_durumu": "Yakın Tehdit",
        "yetenekler": "Muazzam büyüklük ve güce sahiptir, kısa mesafelerde çok hızlı koşabilir."
    }
}